"""Compatibility facade for adventure domain helpers."""

from __future__ import annotations

from .adventure_choices import AdventureChoiceResolver
from .adventure_constants import (
    ADVENTURE_DISCOVERIES,
    ALL_POLICIES,
    ALL_RETREAT_RULES,
    BASE_CRITICAL_RATIO as _BASE_CRITICAL_RATIO,
    BASE_INJURY_CHANCE as _BASE_INJURY_CHANCE,
    CHOICE_PRESS_ON,
    CHOICE_PROCEED_CAUTIOUSLY,
    CHOICE_RETREAT,
    CHOICE_WITHDRAW,
    POLICY_ASSAULT,
    POLICY_CAUTIOUS,
    POLICY_INJURY_MOD,
    POLICY_LOOT_MOD,
    POLICY_RELIC,
    POLICY_RESCUE,
    POLICY_SUPPLY_MOD,
    POLICY_SWIFT,
    POLICY_TREASURE,
    RETREAT_NEVER,
    RETREAT_ON_SERIOUS,
    RETREAT_ON_SUPPLY,
    RETREAT_ON_TROPHY,
    STAT_BASELINE as _STAT_BASELINE,
    SUPPLY_CRITICAL,
    SUPPLY_DEGRADE_FULL_TO_LOW as _SUPPLY_DEGRADE_FULL_TO_LOW,
    SUPPLY_DEGRADE_LOW_TO_CRITICAL as _SUPPLY_DEGRADE_LOW_TO_CRITICAL,
    SUPPLY_FULL,
    SUPPLY_LOW,
    generate_adventure_id,
)
from .adventure_policy import AdventurePolicyEngine, default_retreat_rule_for_policy, select_party_policy
from .adventure_protocols import AdventureRunLike
from .adventure_serialization import AdventureSerialization, TAdventureRun
from .adventure_state_machine import AdventureStateMachine
from .adventure_validation import validate_adventure_run_payload

__all__ = [
    "ADVENTURE_DISCOVERIES",
    "ALL_POLICIES",
    "ALL_RETREAT_RULES",
    "AdventureChoiceResolver",
    "AdventurePolicyEngine",
    "AdventureRunLike",
    "AdventureSerialization",
    "AdventureStateMachine",
    "CHOICE_PRESS_ON",
    "CHOICE_PROCEED_CAUTIOUSLY",
    "CHOICE_RETREAT",
    "CHOICE_WITHDRAW",
    "POLICY_ASSAULT",
    "POLICY_CAUTIOUS",
    "POLICY_INJURY_MOD",
    "POLICY_LOOT_MOD",
    "POLICY_RELIC",
    "POLICY_RESCUE",
    "POLICY_SUPPLY_MOD",
    "POLICY_SWIFT",
    "POLICY_TREASURE",
    "RETREAT_NEVER",
    "RETREAT_ON_SERIOUS",
    "RETREAT_ON_SUPPLY",
    "RETREAT_ON_TROPHY",
    "SUPPLY_CRITICAL",
    "SUPPLY_FULL",
    "SUPPLY_LOW",
    "TAdventureRun",
    "_BASE_CRITICAL_RATIO",
    "_BASE_INJURY_CHANCE",
    "_STAT_BASELINE",
    "_SUPPLY_DEGRADE_FULL_TO_LOW",
    "_SUPPLY_DEGRADE_LOW_TO_CRITICAL",
    "default_retreat_rule_for_policy",
    "generate_adventure_id",
    "select_party_policy",
    "validate_adventure_run_payload",
]
